### ISSUE TITLE
error in receiveMessage

### ISSUE THREAD

**Issue by giuliomoro** [XervoIO/aws-sqs#13]
line 401 of sqs.js reads
  if(opts && opts.VisibilityTimeout) {
This evaluates to false if opts.VisibilityTimeout==0 , which is actually a valid value . I would suggest then to change this line to 
  if(opts && !isNaN(opts.VisibilityTimeout)) {
or
  if(opts && typeof(opts.VisibilityTimeout)=="number") {
Using isNaN allows both strings containing numbers and numbers, while the second option is restricted to numbers.
Additional checks would include that the number is positive and integer ( though I didn't find this in the docs, apparently sqs fails to succeed when a floating point number is passed )

**Comment by tzmanics** [comment]
Hi @giuliomoro  sorry for the big delay in response, and thanks for pointing this out!

We aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `aws-sqs` we'll look into fixing this check.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
